### ISSUE TITLE
[3pt]  - Add tests for items counter - Student A

### ISSUE THREAD

**Issue by SaveryIV** [SaveryIV/Javascript-Capstone-Project#3]
Make sure that function for the items counter is covered with unit tests using Jest. Make sure that you have tests for all edge cases.

**Comment by SaveryIV** [comment]
Link to the PR: https://github.com/SaveryIV/Javascript-Capstone-Project/pull/32

**Comment by laiifuu** [comment]
## Hi team :wave: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

The link you are supposed to submit is a link to a pull request that is opened from the `dev` branch into the `main` branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
